In [2]:
import numpy as np

## 1차원 배열

In [3]:
data = [1,2,3,4,5]

In [4]:
arr = np.array(data)

In [6]:
print(data, type(data),arr,type(arr))

[1, 2, 3, 4, 5] <class 'list'> [1 2 3 4 5] <class 'numpy.ndarray'>


In [7]:
arr.shape #n차원 크기

(5,)

In [8]:
arr.ndim #몇 차원인지 알려줌

1

In [9]:
arr.size #배열의 사이즈(칸 수)

5

In [10]:
arr.dtype

dtype('int32')

In [11]:
f_arr = np.array([1.2,2.3,3.5])
f_arr.dtype

dtype('float64')

In [12]:
arr2 = np.array([1,2,3,4,5], dtype=np.float64)

In [14]:
arr2, arr2.dtype

(array([1., 2., 3., 4., 5.]), dtype('float64'))

# 2차원 배열

In [15]:
data = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(data)

In [16]:
arr.shape

(3, 3)

In [17]:
arr.ndim #몇 차원인지

2

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int32')

# 3차원 배열

In [20]:
data  = [[[1,2,3],[4,5,6],[7,8,9]]]

In [21]:
arr = np.array(data)

In [22]:
arr, type(arr)

(array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]),
 numpy.ndarray)

In [23]:
arr.shape

(1, 3, 3)

In [24]:
arr.size #배열 칸수 

9

# 메서드

- zeros : 0으로 채워진 ndarray 생성
- ones : 1로 채워진 ndarray 생성

In [25]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [26]:
b = np.zeros((4,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
c = np.zeros((3,3,3))
c

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
d = np.ones(3)
d

array([1., 1., 1.])

In [29]:
e = np.ones((3,3))
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# arange

- range와 동일하다
- 총 세 개의 파라미터 (시작범위, 끝 범위, 증감 폭)

In [30]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
b = np.arange(2,101,2)
b

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

# reshape

- 데이터 형태를 바꾼다.


In [32]:
data = np.arange(20)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
data.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
data.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [35]:
data.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# 데이터 타입

- bool : 불린형 (True, False)
- int8 : 정수형 (-2^7 ~ 2^7-1)
- int16 : 정수형 (-2^15 ~ 2^15 -1)
- int32
- unit8 : 부호가 없는 정수형 (0 ~ 2^8 -1)
- unit16 : 부호가 없는 정수형 ( 0 ~ 2^16-1)
```
```
- float16 : 실수형
- float32 : 실수형
- float64 : 실수형 (정확도가 더 좋다)
- string : 문자열



# 인덱싱, 슬라이싱

In [36]:
m = np.array([1,2,3])
m[1]

2

In [38]:
n = np.arange(9).reshape(3,3)
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
n[1][1]

4

In [40]:
n[2][2]

8

In [44]:
### 4,5
### 7,8 
n[1:3, 1:3]

array([[4, 5],
       [7, 8]])

# 수치 연산, 함수
- axio = 0 : 행방향
- axio = 1 : 열방향

- 덧셈 : sum()
- 최댓값, 최솟값 : max(), min()
- 평균 : mena()
- 표준편차 : sid()
- 분산 : val()

In [48]:
d = np.arange(10).reshape(5,2)
d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [49]:
d.sum()

45

In [51]:
d.sum(axis=0)

array([20, 25])

In [53]:
d.sum(axis=1)

array([ 1,  5,  9, 13, 17])

In [54]:
d.min(axis=0)

array([0, 1])

In [55]:
d.max(axis=1)

array([1, 3, 5, 7, 9])